### PR TITLE
Bump Electron & Electron Builder to latest stable versions

### PR DESCRIPTION
**Pull request by kaizoho**
This is a pretty simple PR that:
- Bumps Electron to 11.0.2 and Electron Builder to 22.9.1.
- Removes the package-lock.json file as it is unnecessary and should be generated by npm on the user's machine.
- Adds package-lock.json to the .gitignore file.

If you dislike the removal of package-lock.json I will happily revert.

I've noticed nothing broken from my testing, though further testing by others is appreciated.

### CODE REVIEW

**Comment by D3SOX** [comment]
I don't think you should remove the `package-lock.json`. It is intended to be committed. It guarantees that when someone clones the repo and does a `npm install` they always get the same versions.

**Comment by hmlendea** [comment]
I was following the standard conventions from electron/electron-quick-start which has the package-lock.json unignored.
I think I'd rather keep it.

**Comment by nintendh03s** [comment]
I have restored and updated package-lock.json. I've also removed it from the .gitignore. Building works well on Ubuntu 20.04.1 (amd64) with the latest stable version of NodeJS 14. There are no apparent issues when running the program.

**Review by hmlendea — APPROVED** [review]

**Comment by hmlendea** [comment]
I am going to merge this if you confirm there are no further changes required

**Pull request merged**
