### PR TITLE
Added --lang option to configure GFN language

### PR DESCRIPTION
**Pull request by chriskaya**
This PR adds a `--lang` option to configure GFN lang.
Example:
```
gfn-electron --lang fr_FR
```

I also improved code style, added IPC to communicate between main and preload (required to set lang), and I added a `--open-dev-tools` option to help with debugging.

### CODE REVIEW

**Comment by chriskaya** [comment]
Hi @hmlendea could you review this PR when you have time please? :)

**Comment by herbalizer404** [comment]
Any news?

**Comment by hmlendea** [comment]
Currently there are many conflicts on this PR. I can merge this once they're solved

**Comment by herbalizer404** [comment]
@hmlendea Any workaround to change gfn language from game mode on steam deck?

**Comment by hmlendea** [comment]
None that I know of. Since this app is a wrapper for the GFN website, it always uses the system language

**Pull request closed without merging**
