### PR TITLE
Support for AppImage, deb, apk and snap

### PR DESCRIPTION
**Pull request by JonathanTreffler**
This PR adds some build instruction for the electron builder.

**It adds the following targets:**

**AppImage**: For distribution with one big binary, that can be opened without installation.
**deb**: For installing it on Debian/Ubuntu
**apk**: For installing it on Alpine Linux
**Snap**: For installing it on many Distributions like Ubuntu

I tested the build process and it runs great.
I tested the AppImage and deb version by using them. The others should be fine.

AppImage, deb and apk should be distributed by adding them to the release files on github.
The Snap needs to be uploaded to [snapcraft](https://snapcraft.io/). It should be fairly simple. Heres a [tutorial](https://snapcraft.io/docs/releasing-your-app).

It would probably be a good idea to add a logo, because otherwise the electron logo gets used.

closes: #9

### CODE REVIEW

**Comment by hmlendea** [comment]
I will have to look into this, and into snap, in the weekend.
Thanks for the contribution!

**Comment by popey** [comment]
@hmlendea I work on the snap team at Canonical. I've taken the liberty of pushing your snap to the store. You can find it here: https://snapcraft.io/geforcenow - happy to hand the snap over to you, so you get to publish yourself, but also happy to publish and update on your behalf too. Up to you. Thanks to @JonathanTreffler for doing the necessary work to make the snap build.

**Comment by hmlendea** [comment]
Thank you both @JonathanTreffler and @popey !
Since I am not at all familiar with snap, and even as a user I still use traditional packages (for now at least) I wouldn't feel very comfortable maintaining a snap package. If it's not too much to ask @popey I think it would be best if you continue with that.

Also, as I understood, the snap is not necessary to be included in the GitHub release assets, right?

**Comment by popey** [comment]
@hmlendea no problem. I can continue uploading. I don't mind building it here so you don't need to host the snap in the gh releases page. What's the specific process you're using to build now? Is the readme up to date/accurate?

**Comment by hmlendea** [comment]
Thanks

For me there isn't an issue including the snap file in the assets. I'm just wondering if it is useful at all for regular users.

To build the release packages I simply run `npm run-script build` and electron-builder will build the deb, snap, zip, and apk files.

**Pull request merged**
